# Base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copiar toda a base de código
COPY . .

# Instalar dependências no root do projeto
RUN npm install

# Instalar dependências do backend
WORKDIR /app/apps/backend
RUN npm install

# Construir o backend
WORKDIR /app
RUN npm run build --workspace=@sistema-de-monitoria-ic/backend

# Definir o diretório de trabalho para o backend
WORKDIR /app/apps/backend

# Expor a porta
EXPOSE 5000

# Iniciar o aplicativo
CMD ["npm", "run", "start"] 