import { adminProtectedProcedure, createTRPCRouter } from '@/server/api/trpc'
import { createUserPasswordService } from '@/server/services/user/user-password-service'
import { adminGeneratePasswordResetSchema, adminPasswordResetLinkSchema } from '@/types'
import { BusinessError, ForbiddenError, NotFoundError, ValidationError } from '@/types/errors'
import { logger } from '@/utils/logger'
import { TRPCError } from '@trpc/server'

const log = logger.child({ context: 'UserSupportRouter' })

function mapDomainErrorToTRPCError(error: unknown): TRPCError {
  if (error instanceof NotFoundError) {
    return new TRPCError({ code: 'NOT_FOUND', message: error.message })
  }
  if (error instanceof ForbiddenError) {
    return new TRPCError({ code: 'FORBIDDEN', message: error.message })
  }
  if (error instanceof ValidationError) {
    return new TRPCError({ code: 'BAD_REQUEST', message: error.message })
  }
  if (error instanceof BusinessError) {
    return new TRPCError({ code: 'BAD_REQUEST', message: error.message })
  }
  log.error(error, 'Error generating password reset link')
  return new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: 'Erro ao gerar link de redefinição de senha' })
}

export const userSupportRouter = createTRPCRouter({
  generatePasswordResetLink: adminProtectedProcedure
    .input(adminGeneratePasswordResetSchema)
    .output(adminPasswordResetLinkSchema)
    .mutation(async ({ ctx, input }) => {
      try {
        const service = createUserPasswordService(ctx.db)
        const result = await service.generateResetLink(ctx.user.id, input)
        // The link is only ever returned to the caller, never logged.
        log.info(
          { targetUserId: input.userId, adminId: ctx.user.id, emailSent: result.emailSent },
          'Password reset link generated by admin'
        )
        return result
      } catch (error) {
        throw mapDomainErrorToTRPCError(error)
      }
    }),
})
