/**
 * Lista dos principais bancos brasileiros com código e nome.
 * Fonte: Banco Central do Brasil
 */
export const BANCOS_BRASIL = [
  { codigo: '001', nome: 'Banco do Brasil' },
  { codigo: '003', nome: 'Banco da Amazônia' },
  { codigo: '004', nome: 'Banco do Nordeste' },
  { codigo: '010', nome: 'Credicoamo' },
  { codigo: '011', nome: 'Credit Suisse' },
  { codigo: '012', nome: 'Banco Inbursa' },
  { codigo: '014', nome: 'State Street Brasil' },
  { codigo: '015', nome: 'UBS Brasil' },
  { codigo: '016', nome: 'Sicoob' },
  { codigo: '017', nome: 'BNY Mellon' },
  { codigo: '018', nome: 'Banco Tricury' },
  { codigo: '021', nome: 'Banestes' },
  { codigo: '024', nome: 'Banco Bandepe' },
  { codigo: '025', nome: 'Banco Alfa' },
  { codigo: '029', nome: 'Banco Itaú Consignado' },
  { codigo: '033', nome: 'Santander' },
  { codigo: '036', nome: 'Banco Bradesco BBI' },
  { codigo: '037', nome: 'Banco do Estado do Pará' },
  { codigo: '040', nome: 'Banco Cargill' },
  { codigo: '041', nome: 'Banrisul' },
  { codigo: '047', nome: 'Banco do Estado de Sergipe' },
  { codigo: '062', nome: 'Hipercard' },
  { codigo: '063', nome: 'Banco Bradescard' },
  { codigo: '064', nome: 'Goldman Sachs Brasil' },
  { codigo: '065', nome: 'Banco AndBank' },
  { codigo: '066', nome: 'Banco Morgan Stanley' },
  { codigo: '069', nome: 'Banco Crefisa' },
  { codigo: '070', nome: 'BRB - Banco de Brasília' },
  { codigo: '074', nome: 'Banco J. Safra' },
  { codigo: '075', nome: 'Banco ABN Amro' },
  { codigo: '076', nome: 'Banco KDB Brasil' },
  { codigo: '077', nome: 'Banco Inter' },
  { codigo: '078', nome: 'Haitong Brasil' },
  { codigo: '079', nome: 'Banco Original do Agronegócio' },
  { codigo: '080', nome: 'B&T Corretora de Câmbio' },
  { codigo: '081', nome: 'BBN Banco Brasileiro de Negócios' },
  { codigo: '082', nome: 'Banco Topázio' },
  { codigo: '083', nome: 'Banco da China Brasil' },
  { codigo: '084', nome: 'Uniprime Norte do Paraná' },
  { codigo: '085', nome: 'Cooperativa Central de Crédito - Ailos' },
  { codigo: '089', nome: 'Credisan' },
  { codigo: '091', nome: 'Unicred Central RS' },
  { codigo: '092', nome: 'BRK Financeira' },
  { codigo: '093', nome: 'PóloCred' },
  { codigo: '094', nome: 'Banco Finaxis' },
  { codigo: '095', nome: 'Travelex Banco de Câmbio' },
  { codigo: '096', nome: 'Banco B3' },
  { codigo: '097', nome: 'Credisis' },
  { codigo: '098', nome: 'CrediAlianÇa' },
  { codigo: '099', nome: 'Uniprime Central' },
  { codigo: '104', nome: 'Caixa Econômica Federal' },
  { codigo: '107', nome: 'Banco Bocom BBM' },
  { codigo: '119', nome: 'Banco Western Union' },
  { codigo: '120', nome: 'Banco Rodobens' },
  { codigo: '121', nome: 'Banco Agibank' },
  { codigo: '125', nome: 'Banco Genial' },
  { codigo: '128', nome: 'MS Bank' },
  { codigo: '129', nome: 'UBS Brasil BI' },
  { codigo: '130', nome: 'Caruana' },
  { codigo: '136', nome: 'Unicred' },
  { codigo: '144', nome: 'Bexs Banco de Câmbio' },
  { codigo: '169', nome: 'Banco Olé Bonsucesso Consignado' },
  { codigo: '173', nome: 'BRL Trust DTVM' },
  { codigo: '174', nome: 'Pefisa' },
  { codigo: '177', nome: 'Guide Investimentos' },
  { codigo: '184', nome: 'Banco Itaú BBA' },
  { codigo: '188', nome: 'Ativa Investimentos' },
  { codigo: '208', nome: 'Banco BTG Pactual' },
  { codigo: '212', nome: 'Banco Original' },
  { codigo: '213', nome: 'Banco Arbi' },
  { codigo: '217', nome: 'Banco John Deere' },
  { codigo: '218', nome: 'Banco BS2' },
  { codigo: '222', nome: 'Banco Crédit Agricole' },
  { codigo: '224', nome: 'Banco Fibra' },
  { codigo: '233', nome: 'Banco Cifra' },
  { codigo: '237', nome: 'Bradesco' },
  { codigo: '241', nome: 'Banco Clássico' },
  { codigo: '243', nome: 'Banco Máxima' },
  { codigo: '246', nome: 'Banco ABC Brasil' },
  { codigo: '249', nome: 'Banco Investcred Unibanco' },
  { codigo: '250', nome: 'BCV - Banco de Crédito e Varejo' },
  { codigo: '253', nome: 'Bexs Corretora de Câmbio' },
  { codigo: '254', nome: 'Paraná Banco' },
  { codigo: '260', nome: 'Nu Pagamentos (Nubank)' },
  { codigo: '265', nome: 'Banco Fator' },
  { codigo: '266', nome: 'Banco Cédula' },
  { codigo: '269', nome: 'HSBC Brasil' },
  { codigo: '270', nome: 'Sagitur Corretora de Câmbio' },
  { codigo: '276', nome: 'Banco Senff' },
  { codigo: '278', nome: 'Genial Investimentos' },
  { codigo: '279', nome: 'Cooperativa de Crédito de Primavera do Leste' },
  { codigo: '280', nome: 'Avista' },
  { codigo: '281', nome: 'Cooperativa de Crédito Rural Coopavel' },
  { codigo: '290', nome: 'PagSeguro Internet' },
  { codigo: '299', nome: 'Banco Sorocred' },
  { codigo: '301', nome: 'BPP Instituição de Pagamento' },
  { codigo: '318', nome: 'Banco BMG' },
  { codigo: '320', nome: 'Banco CCB Brasil' },
  { codigo: '323', nome: 'Mercado Pago' },
  { codigo: '329', nome: 'QI Sociedade de Crédito' },
  { codigo: '330', nome: 'Banco Bari' },
  { codigo: '331', nome: 'Fram Capital DTVM' },
  { codigo: '332', nome: 'Acesso Soluções de Pagamento' },
  { codigo: '335', nome: 'Banco Digio' },
  { codigo: '336', nome: 'Banco C6' },
  { codigo: '340', nome: 'Super Pagamentos' },
  { codigo: '341', nome: 'Itaú Unibanco' },
  { codigo: '342', nome: 'Creditas' },
  { codigo: '343', nome: 'FFA' },
  { codigo: '348', nome: 'Banco XP' },
  { codigo: '349', nome: 'Al5' },
  { codigo: '352', nome: 'Toro Investimentos' },
  { codigo: '359', nome: 'Zema Crédito' },
  { codigo: '360', nome: 'Trinus Capital DTVM' },
  { codigo: '362', nome: 'Cielo' },
  { codigo: '363', nome: 'Socopa' },
  { codigo: '364', nome: 'Gerencianet (Efí)' },
  { codigo: '365', nome: 'Solidus CCVM' },
  { codigo: '366', nome: 'Banco Société Générale Brasil' },
  { codigo: '370', nome: 'Banco Mizuho do Brasil' },
  { codigo: '376', nome: 'Banco J.P. Morgan' },
  { codigo: '380', nome: 'PicPay' },
  { codigo: '381', nome: 'Banco Mercedes-Benz' },
  { codigo: '382', nome: 'Fiducia' },
  { codigo: '383', nome: 'Juno' },
  { codigo: '389', nome: 'Banco Mercantil do Brasil' },
  { codigo: '394', nome: 'Banco Bradesco Financiamentos' },
  { codigo: '399', nome: 'Kirton Bank' },
  { codigo: '403', nome: 'Cora' },
  { codigo: '412', nome: 'Banco Capital' },
  { codigo: '422', nome: 'Banco Safra' },
  { codigo: '456', nome: 'Banco MUFG Brasil' },
  { codigo: '461', nome: 'Asaas' },
  { codigo: '473', nome: 'Banco Caixa Geral' },
  { codigo: '477', nome: 'Citibank' },
  { codigo: '487', nome: 'Deutsche Bank' },
  { codigo: '488', nome: 'JPMorgan Chase Bank' },
  { codigo: '492', nome: 'ING Bank' },
  { codigo: '495', nome: 'Banco La Provincia de Buenos Aires' },
  { codigo: '505', nome: 'Banco Credit Suisse' },
  { codigo: '545', nome: 'Senso CCVM' },
  { codigo: '600', nome: 'Banco Luso Brasileiro' },
  { codigo: '604', nome: 'Banco Industrial do Brasil' },
  { codigo: '610', nome: 'Banco VR' },
  { codigo: '611', nome: 'Banco Paulista' },
  { codigo: '612', nome: 'Banco Guanabara' },
  { codigo: '613', nome: 'Omni Banco' },
  { codigo: '623', nome: 'Banco Pan' },
  { codigo: '626', nome: 'Banco C6 Consignado' },
  { codigo: '630', nome: 'Banco Intercap' },
  { codigo: '633', nome: 'Banco Rendimento' },
  { codigo: '634', nome: 'Banco Triângulo' },
  { codigo: '637', nome: 'Banco Sofisa' },
  { codigo: '643', nome: 'Banco Pine' },
  { codigo: '652', nome: 'Itaú Unibanco Holding' },
  { codigo: '653', nome: 'Banco Indusval' },
  { codigo: '654', nome: 'Banco Digimais' },
  { codigo: '655', nome: 'Banco Votorantim' },
  { codigo: '707', nome: 'Banco Daycoval' },
  { codigo: '712', nome: 'Banco Ourinvest' },
  { codigo: '735', nome: 'Banco Neon' },
  { codigo: '739', nome: 'Banco Cetelem' },
  { codigo: '741', nome: 'Banco Ribeirão Preto' },
  { codigo: '743', nome: 'Banco Semear' },
  { codigo: '745', nome: 'Banco Citibank' },
  { codigo: '746', nome: 'Banco Modal' },
  { codigo: '747', nome: 'Banco Rabobank Internacional' },
  { codigo: '748', nome: 'Sicredi' },
  { codigo: '751', nome: 'Scotiabank Brasil' },
  { codigo: '752', nome: 'Banco BNP Paribas' },
  { codigo: '753', nome: 'Novo Banco Continental' },
  { codigo: '754', nome: 'Banco Sistema' },
  { codigo: '755', nome: 'Bank of America Merrill Lynch' },
  { codigo: '756', nome: 'Bancoob (Sicoob)' },
  { codigo: '757', nome: 'Banco KEB Hana do Brasil' },
] as const

export type BancoBrasil = (typeof BANCOS_BRASIL)[number]

/**
 * Valida formato de agência bancária (4 dígitos, opcionalmente com dígito verificador)
 */
export function validarAgencia(agencia: string): boolean {
  const cleaned = agencia.replace(/[^0-9]/g, '')
  return cleaned.length >= 3 && cleaned.length <= 6
}

/**
 * Valida formato de conta bancária (5-12 dígitos, opcionalmente com dígito verificador)
 */
export function validarConta(conta: string): boolean {
  const cleaned = conta.replace(/[^0-9]/g, '')
  return cleaned.length >= 4 && cleaned.length <= 13
}
