/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as IndexTestImport } from './routes/index.test'
import { Route as HomeLayoutImport } from './routes/home/_layout'
import { Route as AuthCasCallbackImport } from './routes/auth/cas-callback'
import { Route as HomeLayoutIndexImport } from './routes/home/_layout/index'
import { Route as HomeLayoutSettingsIndexImport } from './routes/home/_layout/settings/index'
import { Route as HomeLayoutProjectsIndexImport } from './routes/home/_layout/projects/index'
import { Route as HomeLayoutProfileIndexImport } from './routes/home/_layout/profile/index'

// Create Virtual Routes

const HomeImport = createFileRoute('/home')()

// Create/Update Routes

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const IndexTestRoute = IndexTestImport.update({
  id: '/index/test',
  path: '/index/test',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutRoute = HomeLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => HomeRoute,
} as any)

const AuthCasCallbackRoute = AuthCasCallbackImport.update({
  id: '/auth/cas-callback',
  path: '/auth/cas-callback',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutIndexRoute = HomeLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutSettingsIndexRoute = HomeLayoutSettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutProjectsIndexRoute = HomeLayoutProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutProfileIndexRoute = HomeLayoutProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => HomeLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/cas-callback': {
      id: '/auth/cas-callback'
      path: '/auth/cas-callback'
      fullPath: '/auth/cas-callback'
      preLoaderRoute: typeof AuthCasCallbackImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/home/_layout': {
      id: '/home/_layout'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeLayoutImport
      parentRoute: typeof HomeRoute
    }
    '/index/test': {
      id: '/index/test'
      path: '/index/test'
      fullPath: '/index/test'
      preLoaderRoute: typeof IndexTestImport
      parentRoute: typeof rootRoute
    }
    '/home/_layout/': {
      id: '/home/_layout/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeLayoutIndexImport
      parentRoute: typeof HomeLayoutImport
    }
    '/home/_layout/profile/': {
      id: '/home/_layout/profile/'
      path: '/profile'
      fullPath: '/home/profile'
      preLoaderRoute: typeof HomeLayoutProfileIndexImport
      parentRoute: typeof HomeLayoutImport
    }
    '/home/_layout/projects/': {
      id: '/home/_layout/projects/'
      path: '/projects'
      fullPath: '/home/projects'
      preLoaderRoute: typeof HomeLayoutProjectsIndexImport
      parentRoute: typeof HomeLayoutImport
    }
    '/home/_layout/settings/': {
      id: '/home/_layout/settings/'
      path: '/settings'
      fullPath: '/home/settings'
      preLoaderRoute: typeof HomeLayoutSettingsIndexImport
      parentRoute: typeof HomeLayoutImport
    }
  }
}

// Create and export the route tree

interface HomeLayoutRouteChildren {
  HomeLayoutIndexRoute: typeof HomeLayoutIndexRoute
  HomeLayoutProfileIndexRoute: typeof HomeLayoutProfileIndexRoute
  HomeLayoutProjectsIndexRoute: typeof HomeLayoutProjectsIndexRoute
  HomeLayoutSettingsIndexRoute: typeof HomeLayoutSettingsIndexRoute
}

const HomeLayoutRouteChildren: HomeLayoutRouteChildren = {
  HomeLayoutIndexRoute: HomeLayoutIndexRoute,
  HomeLayoutProfileIndexRoute: HomeLayoutProfileIndexRoute,
  HomeLayoutProjectsIndexRoute: HomeLayoutProjectsIndexRoute,
  HomeLayoutSettingsIndexRoute: HomeLayoutSettingsIndexRoute,
}

const HomeLayoutRouteWithChildren = HomeLayoutRoute._addFileChildren(
  HomeLayoutRouteChildren,
)

interface HomeRouteChildren {
  HomeLayoutRoute: typeof HomeLayoutRouteWithChildren
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeLayoutRoute: HomeLayoutRouteWithChildren,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/cas-callback': typeof AuthCasCallbackRoute
  '/home': typeof HomeLayoutRouteWithChildren
  '/index/test': typeof IndexTestRoute
  '/home/': typeof HomeLayoutIndexRoute
  '/home/profile': typeof HomeLayoutProfileIndexRoute
  '/home/projects': typeof HomeLayoutProjectsIndexRoute
  '/home/settings': typeof HomeLayoutSettingsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/cas-callback': typeof AuthCasCallbackRoute
  '/home': typeof HomeLayoutIndexRoute
  '/index/test': typeof IndexTestRoute
  '/home/profile': typeof HomeLayoutProfileIndexRoute
  '/home/projects': typeof HomeLayoutProjectsIndexRoute
  '/home/settings': typeof HomeLayoutSettingsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/cas-callback': typeof AuthCasCallbackRoute
  '/home': typeof HomeRouteWithChildren
  '/home/_layout': typeof HomeLayoutRouteWithChildren
  '/index/test': typeof IndexTestRoute
  '/home/_layout/': typeof HomeLayoutIndexRoute
  '/home/_layout/profile/': typeof HomeLayoutProfileIndexRoute
  '/home/_layout/projects/': typeof HomeLayoutProjectsIndexRoute
  '/home/_layout/settings/': typeof HomeLayoutSettingsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/cas-callback'
    | '/home'
    | '/index/test'
    | '/home/'
    | '/home/profile'
    | '/home/projects'
    | '/home/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/cas-callback'
    | '/home'
    | '/index/test'
    | '/home/profile'
    | '/home/projects'
    | '/home/settings'
  id:
    | '__root__'
    | '/'
    | '/auth/cas-callback'
    | '/home'
    | '/home/_layout'
    | '/index/test'
    | '/home/_layout/'
    | '/home/_layout/profile/'
    | '/home/_layout/projects/'
    | '/home/_layout/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCasCallbackRoute: typeof AuthCasCallbackRoute
  HomeRoute: typeof HomeRouteWithChildren
  IndexTestRoute: typeof IndexTestRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCasCallbackRoute: AuthCasCallbackRoute,
  HomeRoute: HomeRouteWithChildren,
  IndexTestRoute: IndexTestRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/cas-callback",
        "/home",
        "/index/test"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/cas-callback": {
      "filePath": "auth/cas-callback.tsx"
    },
    "/home": {
      "filePath": "home",
      "children": [
        "/home/_layout"
      ]
    },
    "/home/_layout": {
      "filePath": "home/_layout.tsx",
      "parent": "/home",
      "children": [
        "/home/_layout/",
        "/home/_layout/profile/",
        "/home/_layout/projects/",
        "/home/_layout/settings/"
      ]
    },
    "/index/test": {
      "filePath": "index.test.tsx"
    },
    "/home/_layout/": {
      "filePath": "home/_layout/index.tsx",
      "parent": "/home/_layout"
    },
    "/home/_layout/profile/": {
      "filePath": "home/_layout/profile/index.tsx",
      "parent": "/home/_layout"
    },
    "/home/_layout/projects/": {
      "filePath": "home/_layout/projects/index.tsx",
      "parent": "/home/_layout"
    },
    "/home/_layout/settings/": {
      "filePath": "home/_layout/settings/index.tsx",
      "parent": "/home/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
