/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as HomeLayoutImport } from './routes/home/_layout'
import { Route as AuthCasCallbackImport } from './routes/auth/cas-callback'
import { Route as HomeLayoutIndexImport } from './routes/home/_layout/index'
import { Route as HomeLayoutTestIndexImport } from './routes/home/_layout/test/index'
import { Route as HomeLayoutProjectsIndexImport } from './routes/home/_layout/projects/index'
import { Route as HomeLayoutProfileIndexImport } from './routes/home/_layout/profile/index'
import { Route as HomeLayoutOnboardingIndexImport } from './routes/home/_layout/onboarding/index'
import { Route as HomeLayoutAdminUsersImport } from './routes/home/_layout/admin/users'
import { Route as HomeLayoutAdminSeedCursosImport } from './routes/home/_layout/admin/seed-cursos'
import { Route as HomeLayoutAdminFilesImport } from './routes/home/_layout/admin/files'
<<<<<<< Updated upstream
import { Route as HomeLayoutAdminCursosImport } from './routes/home/_layout/admin/cursos'
=======
import { Route as HomeLayoutDashboardStudentIndexImport } from './routes/home/_layout/dashboard/student/index'
import { Route as HomeLayoutDashboardProfessorIndexImport } from './routes/home/_layout/dashboard/professor/index'
import { Route as HomeLayoutDashboardAdminIndexImport } from './routes/home/_layout/dashboard/admin/index'
>>>>>>> Stashed changes

// Create Virtual Routes

const HomeImport = createFileRoute('/home')()

// Create/Update Routes

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutRoute = HomeLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => HomeRoute,
} as any)

const AuthCasCallbackRoute = AuthCasCallbackImport.update({
  id: '/auth/cas-callback',
  path: '/auth/cas-callback',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutIndexRoute = HomeLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutTestIndexRoute = HomeLayoutTestIndexImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutProjectsIndexRoute = HomeLayoutProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutProfileIndexRoute = HomeLayoutProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutOnboardingIndexRoute = HomeLayoutOnboardingIndexImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutAdminUsersRoute = HomeLayoutAdminUsersImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutAdminSeedCursosRoute = HomeLayoutAdminSeedCursosImport.update({
  id: '/admin/seed-cursos',
  path: '/admin/seed-cursos',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutAdminFilesRoute = HomeLayoutAdminFilesImport.update({
  id: '/admin/files',
  path: '/admin/files',
  getParentRoute: () => HomeLayoutRoute,
} as any)

<<<<<<< Updated upstream
const HomeLayoutAdminCursosRoute = HomeLayoutAdminCursosImport.update({
  id: '/admin/cursos',
  path: '/admin/cursos',
  getParentRoute: () => HomeLayoutRoute,
} as any)
=======
const HomeLayoutDashboardStudentIndexRoute =
  HomeLayoutDashboardStudentIndexImport.update({
    id: '/dashboard/student/',
    path: '/dashboard/student/',
    getParentRoute: () => HomeLayoutRoute,
  } as any)

const HomeLayoutDashboardProfessorIndexRoute =
  HomeLayoutDashboardProfessorIndexImport.update({
    id: '/dashboard/professor/',
    path: '/dashboard/professor/',
    getParentRoute: () => HomeLayoutRoute,
  } as any)

const HomeLayoutDashboardAdminIndexRoute =
  HomeLayoutDashboardAdminIndexImport.update({
    id: '/dashboard/admin/',
    path: '/dashboard/admin/',
    getParentRoute: () => HomeLayoutRoute,
  } as any)
>>>>>>> Stashed changes

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/cas-callback': {
      id: '/auth/cas-callback'
      path: '/auth/cas-callback'
      fullPath: '/auth/cas-callback'
      preLoaderRoute: typeof AuthCasCallbackImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/home/_layout': {
      id: '/home/_layout'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeLayoutImport
      parentRoute: typeof HomeRoute
    }
    '/home/_layout/': {
      id: '/home/_layout/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeLayoutIndexImport
      parentRoute: typeof HomeLayoutImport
    }
    '/home/_layout/admin/cursos': {
      id: '/home/_layout/admin/cursos'
      path: '/admin/cursos'
      fullPath: '/home/admin/cursos'
      preLoaderRoute: typeof HomeLayoutAdminCursosImport
      parentRoute: typeof HomeLayoutImport
    }
    '/home/_layout/admin/files': {
      id: '/home/_layout/admin/files'
      path: '/admin/files'
      fullPath: '/home/admin/files'
      preLoaderRoute: typeof HomeLayoutAdminFilesImport
      parentRoute: typeof HomeLayoutImport
    }
    '/home/_layout/admin/seed-cursos': {
      id: '/home/_layout/admin/seed-cursos'
      path: '/admin/seed-cursos'
      fullPath: '/home/admin/seed-cursos'
      preLoaderRoute: typeof HomeLayoutAdminSeedCursosImport
      parentRoute: typeof HomeLayoutImport
    }
    '/home/_layout/admin/users': {
      id: '/home/_layout/admin/users'
      path: '/admin/users'
      fullPath: '/home/admin/users'
      preLoaderRoute: typeof HomeLayoutAdminUsersImport
      parentRoute: typeof HomeLayoutImport
    }
    '/home/_layout/onboarding/': {
      id: '/home/_layout/onboarding/'
      path: '/onboarding'
      fullPath: '/home/onboarding'
      preLoaderRoute: typeof HomeLayoutOnboardingIndexImport
      parentRoute: typeof HomeLayoutImport
    }
    '/home/_layout/profile/': {
      id: '/home/_layout/profile/'
      path: '/profile'
      fullPath: '/home/profile'
      preLoaderRoute: typeof HomeLayoutProfileIndexImport
      parentRoute: typeof HomeLayoutImport
    }
    '/home/_layout/projects/': {
      id: '/home/_layout/projects/'
      path: '/projects'
      fullPath: '/home/projects'
      preLoaderRoute: typeof HomeLayoutProjectsIndexImport
      parentRoute: typeof HomeLayoutImport
    }
    '/home/_layout/test/': {
      id: '/home/_layout/test/'
      path: '/test'
      fullPath: '/home/test'
      preLoaderRoute: typeof HomeLayoutTestIndexImport
      parentRoute: typeof HomeLayoutImport
    }
    '/home/_layout/dashboard/admin/': {
      id: '/home/_layout/dashboard/admin/'
      path: '/dashboard/admin'
      fullPath: '/home/dashboard/admin'
      preLoaderRoute: typeof HomeLayoutDashboardAdminIndexImport
      parentRoute: typeof HomeLayoutImport
    }
    '/home/_layout/dashboard/professor/': {
      id: '/home/_layout/dashboard/professor/'
      path: '/dashboard/professor'
      fullPath: '/home/dashboard/professor'
      preLoaderRoute: typeof HomeLayoutDashboardProfessorIndexImport
      parentRoute: typeof HomeLayoutImport
    }
    '/home/_layout/dashboard/student/': {
      id: '/home/_layout/dashboard/student/'
      path: '/dashboard/student'
      fullPath: '/home/dashboard/student'
      preLoaderRoute: typeof HomeLayoutDashboardStudentIndexImport
      parentRoute: typeof HomeLayoutImport
    }
  }
}

// Create and export the route tree

interface HomeLayoutRouteChildren {
  HomeLayoutIndexRoute: typeof HomeLayoutIndexRoute
  HomeLayoutAdminCursosRoute: typeof HomeLayoutAdminCursosRoute
  HomeLayoutAdminFilesRoute: typeof HomeLayoutAdminFilesRoute
  HomeLayoutAdminSeedCursosRoute: typeof HomeLayoutAdminSeedCursosRoute
  HomeLayoutAdminUsersRoute: typeof HomeLayoutAdminUsersRoute
  HomeLayoutOnboardingIndexRoute: typeof HomeLayoutOnboardingIndexRoute
  HomeLayoutProfileIndexRoute: typeof HomeLayoutProfileIndexRoute
  HomeLayoutProjectsIndexRoute: typeof HomeLayoutProjectsIndexRoute
  HomeLayoutTestIndexRoute: typeof HomeLayoutTestIndexRoute
  HomeLayoutDashboardAdminIndexRoute: typeof HomeLayoutDashboardAdminIndexRoute
  HomeLayoutDashboardProfessorIndexRoute: typeof HomeLayoutDashboardProfessorIndexRoute
  HomeLayoutDashboardStudentIndexRoute: typeof HomeLayoutDashboardStudentIndexRoute
}

const HomeLayoutRouteChildren: HomeLayoutRouteChildren = {
  HomeLayoutIndexRoute: HomeLayoutIndexRoute,
  HomeLayoutAdminCursosRoute: HomeLayoutAdminCursosRoute,
  HomeLayoutAdminFilesRoute: HomeLayoutAdminFilesRoute,
  HomeLayoutAdminSeedCursosRoute: HomeLayoutAdminSeedCursosRoute,
  HomeLayoutAdminUsersRoute: HomeLayoutAdminUsersRoute,
  HomeLayoutOnboardingIndexRoute: HomeLayoutOnboardingIndexRoute,
  HomeLayoutProfileIndexRoute: HomeLayoutProfileIndexRoute,
  HomeLayoutProjectsIndexRoute: HomeLayoutProjectsIndexRoute,
  HomeLayoutTestIndexRoute: HomeLayoutTestIndexRoute,
  HomeLayoutDashboardAdminIndexRoute: HomeLayoutDashboardAdminIndexRoute,
  HomeLayoutDashboardProfessorIndexRoute:
    HomeLayoutDashboardProfessorIndexRoute,
  HomeLayoutDashboardStudentIndexRoute: HomeLayoutDashboardStudentIndexRoute,
}

const HomeLayoutRouteWithChildren = HomeLayoutRoute._addFileChildren(
  HomeLayoutRouteChildren,
)

interface HomeRouteChildren {
  HomeLayoutRoute: typeof HomeLayoutRouteWithChildren
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeLayoutRoute: HomeLayoutRouteWithChildren,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/cas-callback': typeof AuthCasCallbackRoute
  '/home': typeof HomeLayoutRouteWithChildren
  '/home/': typeof HomeLayoutIndexRoute
  '/home/admin/cursos': typeof HomeLayoutAdminCursosRoute
  '/home/admin/files': typeof HomeLayoutAdminFilesRoute
  '/home/admin/seed-cursos': typeof HomeLayoutAdminSeedCursosRoute
  '/home/admin/users': typeof HomeLayoutAdminUsersRoute
  '/home/onboarding': typeof HomeLayoutOnboardingIndexRoute
  '/home/profile': typeof HomeLayoutProfileIndexRoute
  '/home/projects': typeof HomeLayoutProjectsIndexRoute
  '/home/test': typeof HomeLayoutTestIndexRoute
  '/home/dashboard/admin': typeof HomeLayoutDashboardAdminIndexRoute
  '/home/dashboard/professor': typeof HomeLayoutDashboardProfessorIndexRoute
  '/home/dashboard/student': typeof HomeLayoutDashboardStudentIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/cas-callback': typeof AuthCasCallbackRoute
  '/home': typeof HomeLayoutIndexRoute
  '/home/admin/cursos': typeof HomeLayoutAdminCursosRoute
  '/home/admin/files': typeof HomeLayoutAdminFilesRoute
  '/home/admin/seed-cursos': typeof HomeLayoutAdminSeedCursosRoute
  '/home/admin/users': typeof HomeLayoutAdminUsersRoute
  '/home/onboarding': typeof HomeLayoutOnboardingIndexRoute
  '/home/profile': typeof HomeLayoutProfileIndexRoute
  '/home/projects': typeof HomeLayoutProjectsIndexRoute
  '/home/test': typeof HomeLayoutTestIndexRoute
  '/home/dashboard/admin': typeof HomeLayoutDashboardAdminIndexRoute
  '/home/dashboard/professor': typeof HomeLayoutDashboardProfessorIndexRoute
  '/home/dashboard/student': typeof HomeLayoutDashboardStudentIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/cas-callback': typeof AuthCasCallbackRoute
  '/home': typeof HomeRouteWithChildren
  '/home/_layout': typeof HomeLayoutRouteWithChildren
  '/home/_layout/': typeof HomeLayoutIndexRoute
  '/home/_layout/admin/cursos': typeof HomeLayoutAdminCursosRoute
  '/home/_layout/admin/files': typeof HomeLayoutAdminFilesRoute
  '/home/_layout/admin/seed-cursos': typeof HomeLayoutAdminSeedCursosRoute
  '/home/_layout/admin/users': typeof HomeLayoutAdminUsersRoute
  '/home/_layout/onboarding/': typeof HomeLayoutOnboardingIndexRoute
  '/home/_layout/profile/': typeof HomeLayoutProfileIndexRoute
  '/home/_layout/projects/': typeof HomeLayoutProjectsIndexRoute
  '/home/_layout/test/': typeof HomeLayoutTestIndexRoute
  '/home/_layout/dashboard/admin/': typeof HomeLayoutDashboardAdminIndexRoute
  '/home/_layout/dashboard/professor/': typeof HomeLayoutDashboardProfessorIndexRoute
  '/home/_layout/dashboard/student/': typeof HomeLayoutDashboardStudentIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/cas-callback'
    | '/home'
    | '/home/'
    | '/home/admin/cursos'
    | '/home/admin/files'
    | '/home/admin/seed-cursos'
    | '/home/admin/users'
    | '/home/onboarding'
    | '/home/profile'
    | '/home/projects'
    | '/home/test'
    | '/home/dashboard/admin'
    | '/home/dashboard/professor'
    | '/home/dashboard/student'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/cas-callback'
    | '/home'
    | '/home/admin/cursos'
    | '/home/admin/files'
    | '/home/admin/seed-cursos'
    | '/home/admin/users'
    | '/home/onboarding'
    | '/home/profile'
    | '/home/projects'
    | '/home/test'
    | '/home/dashboard/admin'
    | '/home/dashboard/professor'
    | '/home/dashboard/student'
  id:
    | '__root__'
    | '/'
    | '/auth/cas-callback'
    | '/home'
    | '/home/_layout'
    | '/home/_layout/'
    | '/home/_layout/admin/cursos'
    | '/home/_layout/admin/files'
    | '/home/_layout/admin/seed-cursos'
    | '/home/_layout/admin/users'
    | '/home/_layout/onboarding/'
    | '/home/_layout/profile/'
    | '/home/_layout/projects/'
    | '/home/_layout/test/'
    | '/home/_layout/dashboard/admin/'
    | '/home/_layout/dashboard/professor/'
    | '/home/_layout/dashboard/student/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCasCallbackRoute: typeof AuthCasCallbackRoute
  HomeRoute: typeof HomeRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCasCallbackRoute: AuthCasCallbackRoute,
  HomeRoute: HomeRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/cas-callback",
        "/home"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/cas-callback": {
      "filePath": "auth/cas-callback.tsx"
    },
    "/home": {
      "filePath": "home",
      "children": [
        "/home/_layout"
      ]
    },
    "/home/_layout": {
      "filePath": "home/_layout.tsx",
      "parent": "/home",
      "children": [
        "/home/_layout/",
        "/home/_layout/admin/cursos",
        "/home/_layout/admin/files",
        "/home/_layout/admin/seed-cursos",
        "/home/_layout/admin/users",
        "/home/_layout/onboarding/",
        "/home/_layout/profile/",
        "/home/_layout/projects/",
        "/home/_layout/test/",
        "/home/_layout/dashboard/admin/",
        "/home/_layout/dashboard/professor/",
        "/home/_layout/dashboard/student/"
      ]
    },
    "/home/_layout/": {
      "filePath": "home/_layout/index.tsx",
      "parent": "/home/_layout"
    },
    "/home/_layout/admin/cursos": {
      "filePath": "home/_layout/admin/cursos.tsx",
      "parent": "/home/_layout"
    },
    "/home/_layout/admin/files": {
      "filePath": "home/_layout/admin/files.tsx",
      "parent": "/home/_layout"
    },
    "/home/_layout/admin/seed-cursos": {
      "filePath": "home/_layout/admin/seed-cursos.tsx",
      "parent": "/home/_layout"
    },
    "/home/_layout/admin/users": {
      "filePath": "home/_layout/admin/users.tsx",
      "parent": "/home/_layout"
    },
    "/home/_layout/onboarding/": {
      "filePath": "home/_layout/onboarding/index.tsx",
      "parent": "/home/_layout"
    },
    "/home/_layout/profile/": {
      "filePath": "home/_layout/profile/index.tsx",
      "parent": "/home/_layout"
    },
    "/home/_layout/projects/": {
      "filePath": "home/_layout/projects/index.tsx",
      "parent": "/home/_layout"
    },
    "/home/_layout/test/": {
      "filePath": "home/_layout/test/index.tsx",
      "parent": "/home/_layout"
    },
    "/home/_layout/dashboard/admin/": {
      "filePath": "home/_layout/dashboard/admin/index.tsx",
      "parent": "/home/_layout"
    },
    "/home/_layout/dashboard/professor/": {
      "filePath": "home/_layout/dashboard/professor/index.tsx",
      "parent": "/home/_layout"
    },
    "/home/_layout/dashboard/student/": {
      "filePath": "home/_layout/dashboard/student/index.tsx",
      "parent": "/home/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
