#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔨 Executando build..."
npm run build

if [ $? -ne 0 ]; then
  echo "❌ Build falhou. Push cancelado."
  exit 1
fi

echo "🧪 Executando testes..."
npm run test

if [ $? -ne 0 ]; then
  echo "❌ Testes falharam. Push cancelado."
  exit 1
fi

echo "✅ Build e testes passaram. Prosseguindo com o push..." 